name: Mirror Repo and Update (GitCode)

concurrency: concurrency-key

on:
  schedule:
    # Runs every 7 hours from midnight
    - cron: '0 */7 * * *'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-patch:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository (RetroObsession/thpatch_mirror)
    - name: Checkout Repository
      run: |
        git clone https://gitcode.com/RetroObsession/thpatch_mirror.git

    # Step 2: Load the script for mirror patching into the working directory
    - name: Get the mirror script
      run: |
        cd thpatch_mirror
        git clone https://github.com/RetroCyber/thcrap_patch_mirror.git

    # Step 3: Install dependencies for the script in RetroCyber/thcrap_patch_mirror
    - name: Install Python dependencies
      run: |
        cd thpatch_mirror
        python3 -m venv venv
        source venv/bin/activate
        pip install -r ./thcrap_patch_mirror/requirements.txt

    # Step 4: Run the mirror_repo.py script located in RetroCyber/thcrap_patch_mirror
    - name: Run mirror_repo.py
      run: |
        cd thpatch_mirror
        source venv/bin/activate
        python3 ./thcrap_patch_mirror/mirror_repo.py
        rm -rf ./thcrap_patch_mirror/ ./venv/

    # Step 5: Check for changes and commit if there are any
    - name: Commit changes if any
      env:
        GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        TOKEN_NAME: ${{ secrets.GITCODE_TOKEN_NAME }}
        USER_NAME: ${{ secrets.GITCODE_NAME }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
      run: |
        cd thpatch_mirror
        git config user.name "${USER_NAME}"
        git config user.email "${USER_EMAIL}"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "补丁更新：$(date -u '+%Y-%m-%d ===> %H:%M(UTC)')"
          git push -f https://${TOKEN_NAME}:${GITCODE_TOKEN}@gitcode.com/RetroObsession/thpatch_mirror.git
        else
          echo "No changes detected."
        fi