name: Mirror Repo and Update (Gitee)

concurrency: concurrency-key

on:
  schedule:
    # Runs every 6 hours from midnight
    - cron: '0 */6 * * *'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-patch:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository (rc17/thcrap_tsa_mirror)
    - name: Checkout Repository
      run: |
        git clone https://gitee.com/rc17/thcrap_tsa_mirror.git

    # Step 2: Load the script for mirror patching into the working directory
    - name: Get the mirror script
      run: |
        cd thcrap_tsa_mirror
        git clone https://github.com/RetroCyber/thcrap_patch_mirror.git

    # Step 3: Install dependencies for the script in RetroCyber/thcrap_patch_mirror
    - name: Install Python dependencies
      run: |
        cd thcrap_tsa_mirror
        python3 -m venv venv
        source venv/bin/activate
        pip install -r ./thcrap_patch_mirror/requirements.txt

    # Step 4: Run the mirror_repo.py script located in RetroCyber/thcrap_patch_mirror
    - name: Run mirror_repo.py
      run: |
        cd thcrap_tsa_mirror
        source venv/bin/activate
        python3 ./thcrap_patch_mirror/mirror_repo.py
        rm -rf ./thcrap_patch_mirror/ ./venv/

    # Step 5: Check for changes and commit if there are any
    - name: Commit changes if any
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        USER_NAME: ${{ secrets.GITEE_NAME }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
      run: |
        cd thcrap_tsa_mirror
        git config user.name "${USER_NAME}"
        git config user.email "${USER_EMAIL}"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "补丁更新：$(date -u '+%Y-%m-%d ===> %H:%M(UTC)')"
          git push -f https://oauth2:${GITEE_TOKEN}@gitee.com/rc17/thcrap_tsa_mirror.git
        else
          echo "No changes detected."
        fi